@RGS_HostAddress = http://localhost:5062

### Start session
POST {{RGS_HostAddress}}/operator/demo/JungleRelics/start
Content-Type: application/json

{
  "funMode": 1,
  "playerToken": "demo-token"
}

### Base spin (standard mode)
POST {{RGS_HostAddress}}/JungleRelics/play
Content-Type: application/json

{
  "sessionId": "{{sessionId}}",
  "baseBet": 0.2,
  "betMode": "standard",
  "bets": [
    { "betType": "BASE", "amount": 0.2 }
  ]
}

### Buy Free Spins
POST {{RGS_HostAddress}}/JungleRelics/buy-free-spins
Content-Type: application/json

{
  "sessionId": "{{sessionId}}",
  "baseBet": 0.2,
  "betMode": "standard"
}

### Balance Request
POST {{RGS_HostAddress}}/TEST/player/balance
Content-Type: application/json

{
  "playerId": "8bb5289dc906b0420c0d977480acc38d"
}

### Balance Request (Alternative - using session token)
POST {{RGS_HostAddress}}/TEST/player/balance
Content-Type: application/json

{
  "playerId": "demo-token"
}

###
