export const enum GameEvent {
  APP_READY = 'APP_READY',
  START_GAME = 'START_GAME',
  SPIN_REQUEST = 'SPIN_REQUEST',
  SPIN_STARTED = 'SPIN_STARTED',
  SPIN_RESULT = 'SPIN_RESULT',
  RESPIN_STARTED = 'RESPIN_STARTED',
  RESPIN_RESULT = 'RESPIN_RESULT',
  RESPIN_FINISHED = 'RESPIN_FINISHED',
  BALANCE_UPDATED = 'BALANCE_UPDATED',
  BIG_WIN = 'BIG_WIN',
  NETWORK_ERROR = 'NETWORK_ERROR',
  FATAL_ERROR = 'FATAL_ERROR'
}

